# Xamarin.Android and Xamarin.iOS
# Build a Xamarin.Android and Xamarin.iOS app.
# Add steps that test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

jobs:
- job: iOS
  pool:
    vmImage: 'macOS 10.13'
    
- task: Xcode@5
displayName: 'Build the app using Xcode'
inputs:
  actions: 'build'
  sdk: 'iphoneos'
  scheme: 'HelloiOS'
  configuration: 'Debug'
  xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
  useXcpretty: 'false'
